env:
  browser: true
  es2021: true
extends:
  - google
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  max-len: 'off'
  no-unused-vars: 'off'
  react/prop-types: 'off'
  require-jsdoc: 'off'
  valid-jsdoc:
    - error
    - requireReturn: false
      requireParamType: false
      requireReturnType: false
