name: test
on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.json'
      - '**.yml'
  pull_request:
    paths:
      - '!*.md'
jobs:
  test:
    name: Test Start
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # platform: [ windows-latest, macOS-latest ]
        platform: [ ubuntu-latest ]
        node: [ '14' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node }}/${{ matrix.platform }}
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup yarn
        run: |
          npm i -g yarn
          yarn --frozen-lockfile

      - name: Run test
        run: yarn test

      - name: Run lint
        run: yarn lint

      - name: Send Codeclimate
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: abf2b749bbcb4d3fa5a8b8777635b1f2eabecdad54d5fd8babefa41a0e3640e1
        with:
          coverageLocations: |
            ${{github.workspace}}/coverage/lcov.info:lcov
